### ISSUE TITLE
Docker-compose up causes AccessDenied Exception (elastisearch)

### ISSUE THREAD

**Issue by ubhisat** [sherifabdlnaby/elastdocker#4]
Hello,
Thanks for this project. It is very helpful.

I followed the instructions and I see this error when running `make elk`...
> "Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/certs/elastic-certificates.p12",

```
--- (truncated)
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:471) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:163) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:314) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.node.Node.<init>(Node.java:258) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:221) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:221) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:349) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-7.3.0.jar:7.3.0]",
elasticsearch_1  | "... 6 more",
elasticsearch_1  | "Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/config/certs/elastic-certificates.p12",
elasticsearch_1  | "at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]",
elasticsearch_1  | "at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.newByteChannel(Files.java:373) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.newByteChannel(Files.java:424) ~[?:?]",
elasticsearch_1  | "at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420) ~[?:?]",
elasticsearch_1  | "at java.nio.file.Files.newInputStream(Files.java:158) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.core.ssl.TrustConfig.getStore(TrustConfig.java:87) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.core.ssl.StoreTrustConfig.createTrustManager(StoreTrustConfig.java:58) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.core.ssl.SSLService.createSslContext(SSLService.java:382) ~[?:?]",
elasticsearch_1  | "at java.util.HashMap.computeIfAbsent(HashMap.java:1133) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.core.ssl.SSLService.loadSSLConfigurations(SSLService.java:434) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.core.ssl.SSLService.<init>(SSLService.java:119) ~[?:?]",
elasticsearch_1  | "at org.elasticsearch.xpack.core.XPackPlugin.<init>(XPackPlugin.java:146) ~[?:?]",
elasticsearch_1  | "at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]",
elasticsearch_1  | "at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]",
elasticsearch_1  | "at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]",
elasticsearch_1  | "at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500) ~[?:?]",
elasticsearch_1  | "at java.lang.reflect.Constructor.newInstance(Constructor.java:481) ~[?:?]",
--- (truncated)
```

I can provide full logs and other details if needed. 
Thanks again.

**Comment by sherifabdlnaby** [comment]
@ubhisat Are you running on Windows? Linux?

**Comment by sherifabdlnaby** [comment]
@ubhisat I Identified a possible problem, I've pushed a fix.
Please update the repository(setup/setup-certs.sh file to be exact) and validate it's been fixed.

**Comment by ubhisat** [comment]
Confirmed! I do not see that issue anymore.
Thanks for prompt fix!
