### ISSUE TITLE
An illegal reflective access operation has occurred when running make setup

### ISSUE THREAD

**Issue by arudolph-cxt** [sherifabdlnaby/elastdocker#9]
Reproduction:

* clone the repo
* edit .env file to set elasticsearch password (not needed probably)
* run `make setup`

Console output:

```
make setup
make[1]: Entering directory '/home/xxx/elastdocker'
Creating network "elastic_default" with the default driver
Building certs
Step 1/5 : ARG ELK_VERSION
Step 2/5 : FROM docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
7.4.0: Pulling from elasticsearch/elasticsearch
b38629870fdb: Pull complete
4a2fc9d810b8: Pull complete
e2926999e93a: Pull complete
1bfda44c7b09: Pull complete
901547b54de2: Pull complete
7432709cdcf3: Pull complete
5b3b6dd860e9: Pull complete
Digest: sha256:ccacb1463adc6daee970ed45e34cc46c14ba22116b64d5d4fac58044dfd61e8c
Status: Downloaded newer image for docker.elastic.co/elasticsearch/elasticsearch:7.4.0
 ---> dd156dd42341
Step 3/5 : COPY scripts/docker-healthcheck .
 ---> 85e7b710f4a3
Step 4/5 : HEALTHCHECK CMD sh ./docker-healthcheck
 ---> Running in d9b49dcb0400
Removing intermediate container d9b49dcb0400
 ---> d6b7577dff83
Step 5/5 : RUN elasticsearch-plugin install --batch repository-s3
 ---> Running in 9e523ba7f528
-> Downloading repository-s3 from elastic
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission es.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed repository-s3
Removing intermediate container 9e523ba7f528
 ---> 0ebae034c3b0

Successfully built 0ebae034c3b0
Successfully tagged elastic_certs:latest
WARNING: Image for service certs was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
====== Generating Elasticsearch Certifications ======
=====================================================
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/usr/share/elasticsearch/lib/tools/security-cli/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.nio.file.AccessDeniedException: /secrets/certs/elastic-stack-ca.p12
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:478)
	at java.base/java.nio.file.Files.newOutputStream(Files.java:223)
	at org.elasticsearch.xpack.security.cli.CertificateTool.fullyWriteFile(CertificateTool.java:994)
	at org.elasticsearch.xpack.security.cli.CertificateTool.access$800(CertificateTool.java:85)
	at org.elasticsearch.xpack.security.cli.CertificateTool$CertificateAuthorityCommand.writeCertificateAuthority(CertificateTool.java:876)
	at org.elasticsearch.xpack.security.cli.CertificateTool$CertificateAuthorityCommand.execute(CertificateTool.java:867)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:125)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.xpack.security.cli.CertificateTool.main(CertificateTool.java:137)
Makefile:21: recipe for target 'certs' failed
make[1]: *** [certs] Error 1
make[1]: Leaving directory '/home/xxx/elastdocker'
Makefile:24: recipe for target 'setup' failed
make: *** [setup] Error 2
```
Any subsequent rerun triggers the same warning/error.

**Comment by sherifabdlnaby** [comment]
I was unable to reproduce the bug, it seems like a folder permission issue, can you confirm?

**Comment by arudolph-cxt** [comment]
seems like this was the issue. I got it working in the meantime.
